### ISSUE TITLE
wlan requires UseDomains in order for autoproxy to work

### ISSUE THREAD

**Issue by rustylynch** [clearlinux-pkgs/clr-systemd-config#1]
When connecting to a wifi network behind a firewall the autoproxy is unable to resolve the PAC url because the 80-wlan.network configuration file is not enabling UseDomains=yes in the [DHCP] section.

Index: clr-systemd-config-149/network/80-wlan.network
===================================================================
--- clr-systemd-config-149.orig/network/80-wlan.network	2018-02-08 11:48:27.000000000 -0800
+++ clr-systemd-config-149/network/80-wlan.network	2018-03-17 18:56:18.586759088 -0700
@@ -5,4 +5,5 @@
 DHCP=both
 
 [DHCP]
+UseDomains=yes
 UseMTU=yes

**Comment by seanvk** [comment]
We're wanting issues to be filed in https://github.com/clearlinux/distribution/issues

We'll need to communicate this better at the clearlinux-pkgs level.

Adding @sofar 

Rusty, I'll refile this for you on https://github.com/clearlinux/distribution/issues

Sean

**Comment by seanvk** [comment]
Moved to https://github.com/clearlinux/distribution/issues/25

Done.

@ahkok Can you close this one?

Thanks,

Sean
